### ISSUE TITLE
Can no longer pull misterio92/ci-php-node:2.0

### ISSUE THREAD

**Issue by marcaddeo** [vyuldashev/docker-ci-php-node#1]
Seems like it just started today, but I can no longer pull `misterio92/ci-php-node:2.0` which is breaking our automated builds.

**Comment by vyuldashev** [comment]
Hello, I am working on making automating docker builds. Everything will be restored today.

**Comment by marcaddeo** [comment]
Okay, thank you!

**Comment by vyuldashev** [comment]
@marcaddeo Should be fixed now.
