### ISSUE TITLE
Node version update caused node-sass incompability

### ISSUE THREAD

**Issue by fmvnow** [vyuldashev/docker-ci-php-node#2]
Hi, 
I noticed, in some deploys using your docker image, that after you updated the node version it started to get errors with node-sass dependency. 

When I turned back to LTS node-10.15.3  all dependencies installed normally again. Maybe it was good to keep an LTS node version alive. :) 

Tks

**Comment by vyuldashev** [comment]
```rm -rf node_modules ; rm -f package-lock.json ; npm install```, then commit package-lock.json again. The problem should be fixed.
